# Generated by Django 3.2 on 2025-01-07 04:58

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=core.models.CustomDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_price',
            field=core.models.CustomDecimalField(decimal_places=2, max_digits=10),
        ),
    ]
